apiVersion: apps/v1
kind: Deployment
metadata:
  name: agenthub-api
  labels:
    app: agenthub-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agenthub-api
  template:
    metadata:
      labels:
        app: agenthub-api
    spec:
      containers:
        - name: api
          image: your-registry/agenthub-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: agenthub-config
                  key: NODE_ENV
            - name: PORT
              value: "3000"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: agenthub-secrets
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: agenthub-secrets
                  key: JWT_SECRET
            - name: CORS_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: agenthub-config
                  key: CORS_ORIGINS
            - name: RATE_LIMIT_WINDOW_MS
              valueFrom:
                configMapKeyRef:
                  name: agenthub-config
                  key: RATE_LIMIT_WINDOW_MS
            - name: RATE_LIMIT_MAX
              valueFrom:
                configMapKeyRef:
                  name: agenthub-config
                  key: RATE_LIMIT_MAX
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
