#!/bin/bash

echo "🚀 Setting up Enhanced AgentHub Database Schema..."

# Check if we have the necessary environment variables
if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_SERVICE_ROLE_KEY" ]; then
    echo "❌ Error: Please set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY environment variables"
    echo ""
    echo "You can find these in your Supabase project settings under API:"
    echo "1. Go to https://app.supabase.com"
    echo "2. Select your project"
    echo "3. Go to Settings > API"
    echo "4. Copy the Project URL and service_role key"
    echo ""
    echo "Then run:"
    echo "export SUPABASE_URL='your_project_url'"
    echo "export SUPABASE_SERVICE_ROLE_KEY='your_service_role_key'"
    echo ""
    exit 1
fi

echo "🗄️  Setting up enhanced database schema for conversational flows..."

echo ""
echo "📋 Manual Setup Instructions:"
echo ""
echo "Since automated SQL execution can be complex, please follow these steps:"
echo ""
echo "1. � Copy the enhanced_database_schema.sql content:"
echo "   - File location: $(pwd)/enhanced_database_schema.sql"
echo ""
echo "2. 🌐 Go to your Supabase project dashboard:"
echo "   - Visit: https://app.supabase.com"
echo "   - Select your project"
echo ""
echo "3. ⚙️  Open the SQL Editor:"
echo "   - Click on 'SQL Editor' in the left sidebar"
echo "   - Click 'New Query'"
echo ""
echo "4. 📝 Paste and execute the schema:"
echo "   - Copy all content from enhanced_database_schema.sql"
echo "   - Paste it into the SQL Editor"
echo "   - Click 'Run' to execute"
echo ""
echo "5. ✅ Verify the tables were created:"
echo "   - Check that these tables exist in your database:"
echo "     • clients"
echo "     • interactions"
echo "     • contracts"
echo "     • contract_events"
echo "     • showings"
echo "     • property_listings"
echo "     • client_properties"
echo "     • scheduled_messages"
echo "     • agent_calendar"
echo ""

# Check if the schema file exists
if [ ! -f "enhanced_database_schema.sql" ]; then
    echo "❌ Error: enhanced_database_schema.sql not found in current directory"
    echo "Please run this script from the agentHub project root directory"
    exit 1
fi

echo "📄 Schema file confirmed at: $(pwd)/enhanced_database_schema.sql"
echo ""

echo "🎉 After you've run the SQL schema, your database will support:"
echo "   • 👥 Client management with interaction tracking"
echo "   • 📋 Contract creation and amendment workflows"
echo "   • 🏠 Showing scheduling with calendar integration"
echo "   • 💬 Follow-up message generation and scheduling"
echo "   • 🏘️  Property listings and client property tracking"
echo ""

echo "🚀 Next steps:"
echo ""
echo "1. 🔧 Start your backend server:"
echo "   cd backend && npm start"
echo ""
echo "2. 🌐 Start your frontend application:"
echo "   cd frontend && npm start"
echo ""
echo "3. � Access the new features:"
echo "   - Login to your AgentHub application"
echo "   - Click the new 'AI Flows' tab"
echo "   - Use the 'Add Sample Data' button for testing"
echo ""
echo "4. 🧪 Test the conversational flows:"
echo "   - Try the Contract Amendment flow"
echo "   - Test Follow-up Generation with your clients"
echo "   - Schedule property showings"
echo ""

echo "💡 Troubleshooting:"
echo "   - If you get permission errors, ensure you're using the service_role key"
echo "   - If auth.uid() errors occur, use the sample data API endpoint instead"
echo "   - Check the browser console for any JavaScript errors"
echo ""

echo "📚 Documentation:"
echo "   - See CONVERSATIONAL_FLOWS_README.md for detailed usage instructions"
echo "   - Sample data can be added via the API endpoint: POST /api/setup/sample-data"
echo ""
